// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: koinos/rpc/mempool/mempool_rpc.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Koinos_Rpc_Mempool_pending_transaction {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var transaction: Koinos_Protocol_transaction {
    get {return _transaction ?? Koinos_Protocol_transaction()}
    set {_transaction = newValue}
  }
  /// Returns true if `transaction` has been explicitly set.
  var hasTransaction: Bool {return self._transaction != nil}
  /// Clears the value of `transaction`. Subsequent reads from it will return its default value.
  mutating func clearTransaction() {self._transaction = nil}

  var diskStorageUsed: UInt64 = 0

  var networkBandwidthUsed: UInt64 = 0

  var computeBandwidthUsed: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _transaction: Koinos_Protocol_transaction? = nil
}

struct Koinos_Rpc_Mempool_check_pending_account_resources_request {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var payer: Data = Data()

  var maxPayerRc: UInt64 = 0

  var rcLimit: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Koinos_Rpc_Mempool_check_pending_account_resources_response {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var success: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Koinos_Rpc_Mempool_get_pending_transactions_request {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var limit: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Koinos_Rpc_Mempool_get_pending_transactions_response {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pendingTransactions: [Koinos_Rpc_Mempool_pending_transaction] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Koinos_Rpc_Mempool_mempool_request {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var request: Koinos_Rpc_Mempool_mempool_request.OneOf_Request? = nil

  var reserved: Koinos_Rpc_reserved_rpc {
    get {
      if case .reserved(let v)? = request {return v}
      return Koinos_Rpc_reserved_rpc()
    }
    set {request = .reserved(newValue)}
  }

  var checkPendingAccountResources: Koinos_Rpc_Mempool_check_pending_account_resources_request {
    get {
      if case .checkPendingAccountResources(let v)? = request {return v}
      return Koinos_Rpc_Mempool_check_pending_account_resources_request()
    }
    set {request = .checkPendingAccountResources(newValue)}
  }

  var getPendingTransactions: Koinos_Rpc_Mempool_get_pending_transactions_request {
    get {
      if case .getPendingTransactions(let v)? = request {return v}
      return Koinos_Rpc_Mempool_get_pending_transactions_request()
    }
    set {request = .getPendingTransactions(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Request: Equatable {
    case reserved(Koinos_Rpc_reserved_rpc)
    case checkPendingAccountResources(Koinos_Rpc_Mempool_check_pending_account_resources_request)
    case getPendingTransactions(Koinos_Rpc_Mempool_get_pending_transactions_request)

  #if !swift(>=4.1)
    static func ==(lhs: Koinos_Rpc_Mempool_mempool_request.OneOf_Request, rhs: Koinos_Rpc_Mempool_mempool_request.OneOf_Request) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.reserved, .reserved): return {
        guard case .reserved(let l) = lhs, case .reserved(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.checkPendingAccountResources, .checkPendingAccountResources): return {
        guard case .checkPendingAccountResources(let l) = lhs, case .checkPendingAccountResources(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.getPendingTransactions, .getPendingTransactions): return {
        guard case .getPendingTransactions(let l) = lhs, case .getPendingTransactions(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  init() {}
}

struct Koinos_Rpc_Mempool_mempool_response {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var response: Koinos_Rpc_Mempool_mempool_response.OneOf_Response? = nil

  var reserved: Koinos_Rpc_reserved_rpc {
    get {
      if case .reserved(let v)? = response {return v}
      return Koinos_Rpc_reserved_rpc()
    }
    set {response = .reserved(newValue)}
  }

  var error: Koinos_Rpc_error_response {
    get {
      if case .error(let v)? = response {return v}
      return Koinos_Rpc_error_response()
    }
    set {response = .error(newValue)}
  }

  var checkPendingAccountResources: Koinos_Rpc_Mempool_check_pending_account_resources_response {
    get {
      if case .checkPendingAccountResources(let v)? = response {return v}
      return Koinos_Rpc_Mempool_check_pending_account_resources_response()
    }
    set {response = .checkPendingAccountResources(newValue)}
  }

  var getPendingTransactions: Koinos_Rpc_Mempool_get_pending_transactions_response {
    get {
      if case .getPendingTransactions(let v)? = response {return v}
      return Koinos_Rpc_Mempool_get_pending_transactions_response()
    }
    set {response = .getPendingTransactions(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Response: Equatable {
    case reserved(Koinos_Rpc_reserved_rpc)
    case error(Koinos_Rpc_error_response)
    case checkPendingAccountResources(Koinos_Rpc_Mempool_check_pending_account_resources_response)
    case getPendingTransactions(Koinos_Rpc_Mempool_get_pending_transactions_response)

  #if !swift(>=4.1)
    static func ==(lhs: Koinos_Rpc_Mempool_mempool_response.OneOf_Response, rhs: Koinos_Rpc_Mempool_mempool_response.OneOf_Response) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.reserved, .reserved): return {
        guard case .reserved(let l) = lhs, case .reserved(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.error, .error): return {
        guard case .error(let l) = lhs, case .error(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.checkPendingAccountResources, .checkPendingAccountResources): return {
        guard case .checkPendingAccountResources(let l) = lhs, case .checkPendingAccountResources(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.getPendingTransactions, .getPendingTransactions): return {
        guard case .getPendingTransactions(let l) = lhs, case .getPendingTransactions(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension Koinos_Rpc_Mempool_pending_transaction: @unchecked Sendable {}
extension Koinos_Rpc_Mempool_check_pending_account_resources_request: @unchecked Sendable {}
extension Koinos_Rpc_Mempool_check_pending_account_resources_response: @unchecked Sendable {}
extension Koinos_Rpc_Mempool_get_pending_transactions_request: @unchecked Sendable {}
extension Koinos_Rpc_Mempool_get_pending_transactions_response: @unchecked Sendable {}
extension Koinos_Rpc_Mempool_mempool_request: @unchecked Sendable {}
extension Koinos_Rpc_Mempool_mempool_request.OneOf_Request: @unchecked Sendable {}
extension Koinos_Rpc_Mempool_mempool_response: @unchecked Sendable {}
extension Koinos_Rpc_Mempool_mempool_response.OneOf_Response: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "koinos.rpc.mempool"

extension Koinos_Rpc_Mempool_pending_transaction: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".pending_transaction"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "transaction"),
    2: .standard(proto: "disk_storage_used"),
    3: .standard(proto: "network_bandwidth_used"),
    4: .standard(proto: "compute_bandwidth_used"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._transaction) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.diskStorageUsed) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.networkBandwidthUsed) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.computeBandwidthUsed) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._transaction {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.diskStorageUsed != 0 {
      try visitor.visitSingularUInt64Field(value: self.diskStorageUsed, fieldNumber: 2)
    }
    if self.networkBandwidthUsed != 0 {
      try visitor.visitSingularUInt64Field(value: self.networkBandwidthUsed, fieldNumber: 3)
    }
    if self.computeBandwidthUsed != 0 {
      try visitor.visitSingularUInt64Field(value: self.computeBandwidthUsed, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Koinos_Rpc_Mempool_pending_transaction, rhs: Koinos_Rpc_Mempool_pending_transaction) -> Bool {
    if lhs._transaction != rhs._transaction {return false}
    if lhs.diskStorageUsed != rhs.diskStorageUsed {return false}
    if lhs.networkBandwidthUsed != rhs.networkBandwidthUsed {return false}
    if lhs.computeBandwidthUsed != rhs.computeBandwidthUsed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Koinos_Rpc_Mempool_check_pending_account_resources_request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".check_pending_account_resources_request"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "payer"),
    2: .standard(proto: "max_payer_rc"),
    3: .standard(proto: "rc_limit"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.payer) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.maxPayerRc) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.rcLimit) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.payer.isEmpty {
      try visitor.visitSingularBytesField(value: self.payer, fieldNumber: 1)
    }
    if self.maxPayerRc != 0 {
      try visitor.visitSingularUInt64Field(value: self.maxPayerRc, fieldNumber: 2)
    }
    if self.rcLimit != 0 {
      try visitor.visitSingularUInt64Field(value: self.rcLimit, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Koinos_Rpc_Mempool_check_pending_account_resources_request, rhs: Koinos_Rpc_Mempool_check_pending_account_resources_request) -> Bool {
    if lhs.payer != rhs.payer {return false}
    if lhs.maxPayerRc != rhs.maxPayerRc {return false}
    if lhs.rcLimit != rhs.rcLimit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Koinos_Rpc_Mempool_check_pending_account_resources_response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".check_pending_account_resources_response"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "success"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Koinos_Rpc_Mempool_check_pending_account_resources_response, rhs: Koinos_Rpc_Mempool_check_pending_account_resources_response) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Koinos_Rpc_Mempool_get_pending_transactions_request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".get_pending_transactions_request"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "limit"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt64Field(value: &self.limit) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.limit != 0 {
      try visitor.visitSingularUInt64Field(value: self.limit, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Koinos_Rpc_Mempool_get_pending_transactions_request, rhs: Koinos_Rpc_Mempool_get_pending_transactions_request) -> Bool {
    if lhs.limit != rhs.limit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Koinos_Rpc_Mempool_get_pending_transactions_response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".get_pending_transactions_response"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "pending_transactions"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.pendingTransactions) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.pendingTransactions.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.pendingTransactions, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Koinos_Rpc_Mempool_get_pending_transactions_response, rhs: Koinos_Rpc_Mempool_get_pending_transactions_response) -> Bool {
    if lhs.pendingTransactions != rhs.pendingTransactions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Koinos_Rpc_Mempool_mempool_request: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".mempool_request"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "reserved"),
    2: .standard(proto: "check_pending_account_resources"),
    3: .standard(proto: "get_pending_transactions"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Koinos_Rpc_reserved_rpc?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .reserved(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .reserved(v)
        }
      }()
      case 2: try {
        var v: Koinos_Rpc_Mempool_check_pending_account_resources_request?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .checkPendingAccountResources(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .checkPendingAccountResources(v)
        }
      }()
      case 3: try {
        var v: Koinos_Rpc_Mempool_get_pending_transactions_request?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .getPendingTransactions(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .getPendingTransactions(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.request {
    case .reserved?: try {
      guard case .reserved(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .checkPendingAccountResources?: try {
      guard case .checkPendingAccountResources(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .getPendingTransactions?: try {
      guard case .getPendingTransactions(let v)? = self.request else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Koinos_Rpc_Mempool_mempool_request, rhs: Koinos_Rpc_Mempool_mempool_request) -> Bool {
    if lhs.request != rhs.request {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Koinos_Rpc_Mempool_mempool_response: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".mempool_response"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "reserved"),
    2: .same(proto: "error"),
    3: .standard(proto: "check_pending_account_resources"),
    4: .standard(proto: "get_pending_transactions"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Koinos_Rpc_reserved_rpc?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .reserved(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .reserved(v)
        }
      }()
      case 2: try {
        var v: Koinos_Rpc_error_response?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .error(v)
        }
      }()
      case 3: try {
        var v: Koinos_Rpc_Mempool_check_pending_account_resources_response?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .checkPendingAccountResources(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .checkPendingAccountResources(v)
        }
      }()
      case 4: try {
        var v: Koinos_Rpc_Mempool_get_pending_transactions_response?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .getPendingTransactions(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .getPendingTransactions(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.response {
    case .reserved?: try {
      guard case .reserved(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .error?: try {
      guard case .error(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .checkPendingAccountResources?: try {
      guard case .checkPendingAccountResources(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .getPendingTransactions?: try {
      guard case .getPendingTransactions(let v)? = self.response else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Koinos_Rpc_Mempool_mempool_response, rhs: Koinos_Rpc_Mempool_mempool_response) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
